/**
 * Builds src/lib/catalog.generated.ts (REAL catalog: names, prices, Cloudinary
 * images) from JSON pulled from the backend API.
 *
 * Refresh the catalog after admin changes:
 *   1) curl the API pages to the data files below (see scripts/refresh-catalog.sh)
 *   2) node scripts/gen-catalog.mjs
 * (fetch is done via curl to avoid a Node-25 libuv teardown crash on Windows.)
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const DATA_DIR = process.env.CATALOG_DATA_DIR ?? path.resolve("scripts/data");

const readJson = (f) => JSON.parse(readFileSync(path.join(DATA_DIR, f), "utf8"));

const items = [
  ...readJson("prods1.json").items,
  ...readJson("prods2.json").items,
  ...readJson("prods3.json").items,
];
const cats = readJson("cats.json");

let idCounter = 1;
const products = items.map((p) => ({
  id: idCounter++,
  apiId: p.id, // backend cuid
  slug: p.slug,
  name: p.name,
  category: p.category ?? "uncategorized",
  categoryName: p.categoryName ?? "Shop",
  material: p.material ?? "",
  price: p.price,
  oldPrice: p.oldPrice ?? undefined,
  rating: p.rating || 0,
  reviews: p.reviews || 0,
  sales: p.sales || 0,
  badges: p.badges ?? [],
  colors: p.colors ?? [],
  inStock: p.inStock,
  sku: "RX-" + String(1000 + idCounter),
  images: p.images?.length ? p.images : [],
  short: p.short || p.categoryName || "",
}));

const categories = cats.map((c) => ({
  slug: c.slug,
  name: c.name,
  description: c.description || "",
  products: c.products,
  image: c.image || "/images/categories/luxury.jpg",
  featured: c.featured,
}));

const header = `// AUTO-GENERATED by scripts/gen-catalog.mjs — do not edit by hand.
// Real ROSYNX catalog pulled from the backend API (Neon + Cloudinary).
import type { Product } from "./data";

export const generatedProducts: Product[] = ${JSON.stringify(products, null, 2)};

export const generatedCategories = ${JSON.stringify(categories, null, 2)};
`;

const out = path.resolve("src/lib/catalog.generated.ts");
writeFileSync(out, header);
console.log(`Wrote ${products.length} products, ${categories.length} categories -> ${out}`);
